# Generated by Django 3.0.2 on 2020-01-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=128, verbose_name='Libelle')),
                ('prix', models.FloatField(default=0.0, verbose_name='Prix')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.FloatField(default=0.0, verbose_name='Pourcentage')),
                ('qrCode', models.CharField(max_length=20, verbose_name='Qrcode')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Article', verbose_name='Article')),
            ],
        ),
    ]
