# Generated by Django 3.0.2 on 2020-03-18 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libelle')),
                ('description', models.TextField(max_length=1200, verbose_name='Description')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Date début')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Date fin')),
                ('pourcentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Pourcentage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('active', models.BooleanField(default=False, verbose_name='Active?')),
            ],
        ),
    ]
