# Generated by Django 3.0.3 on 2020-03-27 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=1200, verbose_name='Description')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
                ('percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Image')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='Qrcode')),
                ('active', models.BooleanField(default=False, verbose_name='Active ?')),
            ],
        ),
    ]
