# Generated by Django 3.0.2 on 2020-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage',
            field=models.FloatField(default=0.0, verbose_name='Pourcentage'),
        ),
    ]
