# Generated by Django 3.0.2 on 2020-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='article',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='qrCode',
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date fin'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='libelle',
            field=models.CharField(max_length=255, null=True, verbose_name='Libelle'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date début'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
