# Generated by Django 3.0.2 on 2020-01-14 07:49

from django.db import migrations


def add_articles(apps, schema_editor):
    for i in range(0, 5):
        article =

class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
    ]
