# Generated by Django 3.0.3 on 2020-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Promotion code'),
        ),
    ]
